"""apply_character_stats_and_test_player_column

Revision ID: 392d1d6ef02b
Revises: 54d0d42b9f28
Create Date: 2025-05-30 14:44:50.925708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392d1d6ef02b'
down_revision: Union[str, None] = '54d0d42b9f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - MODIFIED WITH SERVER DEFAULTS ###
    op.add_column('characters', sa.Column('strength', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('dexterity', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('constitution', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('intelligence', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('wisdom', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('charisma', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('luck', sa.Integer(), nullable=False, server_default=sa.text('5'))) # Defaulted to 5 in model
    op.add_column('characters', sa.Column('current_health', sa.Integer(), nullable=False, server_default=sa.text('20')))
    op.add_column('characters', sa.Column('max_health', sa.Integer(), nullable=False, server_default=sa.text('20')))
    op.add_column('characters', sa.Column('current_mana', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('max_mana', sa.Integer(), nullable=False, server_default=sa.text('10')))
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('characters', sa.Column('experience_points', sa.Integer(), nullable=False, server_default=sa.text('0')))
    
    # learned_skills and learned_traits are nullable=True in your model, so server_default is optional here,
    # but good if you want existing rows to have an empty list instead of NULL.
    # If your model actually defines them as NON-OPTIONAL (e.g. Mapped[List[str]]), then nullable=False here.
    # Based on Mapped[Optional[List[str]]], nullable=True is correct.
    op.add_column('characters', sa.Column('learned_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text("'[]'::jsonb"), comment='List of skill identifiers learned by the character'))
    op.add_column('characters', sa.Column('learned_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text("'[]'::jsonb"), comment='List of trait identifiers acquired by the character'))
    
    op.add_column('characters', sa.Column('base_ac', sa.Integer(), nullable=False, server_default=sa.text('10'), comment='Base Armor Class'))
    op.add_column('characters', sa.Column('base_attack_bonus', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='Base to-hit bonus'))
    op.add_column('characters', sa.Column('base_damage_dice', sa.String(length=20), nullable=False, server_default=sa.text("'1d4'"), comment='e.g., 1d6'))
    op.add_column('characters', sa.Column('base_damage_bonus', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='Base flat damage bonus'))    
    
    # Assuming you still have the test column for players, and it's nullable
    # If you removed it from the model, remove this line.    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - MODIFIED (ensure test_column is dropped if added) ###    

    op.drop_column('characters', 'base_damage_bonus')
    op.drop_column('characters', 'base_damage_dice')
    op.drop_column('characters', 'base_attack_bonus')
    op.drop_column('characters', 'base_ac')
    op.drop_column('characters', 'learned_traits')
    op.drop_column('characters', 'learned_skills')
    op.drop_column('characters', 'experience_points')
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'max_mana')
    op.drop_column('characters', 'current_mana')
    op.drop_column('characters', 'max_health')
    op.drop_column('characters', 'current_health')
    op.drop_column('characters', 'luck')
    op.drop_column('characters', 'charisma')
    op.drop_column('characters', 'wisdom')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'constitution')
    op.drop_column('characters', 'dexterity')
    op.drop_column('characters', 'strength')
    # ### end Alembic commands ###