"""add_character_class_template_fk_to_character_AUTO

Revision ID: 55e573623d46
Revises: 392d1d6ef02b
Create Date: 2025-05-30 16:01:57.961649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55e573623d46'
down_revision: Union[str, None] = '392d1d6ef02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_class_template_id', sa.UUID(), nullable=True))
    op.alter_column('characters', 'learned_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of skill identifiers learned by the character',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('characters', 'learned_traits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of trait identifiers acquired by the character',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_foreign_key(None, 'characters', 'character_class_templates', ['character_class_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey') # type: ignore
    op.alter_column('characters', 'learned_traits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of trait identifiers acquired by the character',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('characters', 'learned_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of skill identifiers learned by the character',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('characters', 'character_class_template_id')
    # ### end Alembic commands ###
